### ISSUE TITLE
build failing for 0.56.2

### ISSUE THREAD

**Issue by raybellwaves** [conda-forge/numba-feedstock#100]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The bot build for 0.56.2 is failing https://github.com/conda-forge/numba-feedstock/pull/99

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by raybellwaves** [comment]
Moving my notes out of the PR to here...

Taking a look at one of the failing builds (linux linux_64_numpy1.21python3.10.____cpython) (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=562062&view=logs&jobId=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de) I see

```
Applying patch: /home/conda/recipe_root/patch-parfor.patch with args:
['-Np1', '-i', '/tmp/tmpat4sfdzr/patch-parfor.patch.native', '--binary']
checking file numba/tests/test_parfors.py
Hunk #1 FAILED at 63.
1 out of 1 hunk FAILED
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/opt/conda/bin/patch', '--no-backup-if-mismatch', '--batch', '-Np1', '-i', '/tmp/tmpat4sfdzr/patch-parfor.patch.native', '--binary', '--dry-run']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 239, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 211, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3091, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2141, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/render.py", line 662, in try_download
    raise RuntimeError("Failed to download or patch source. Please see build log for info.")
RuntimeError: Failed to download or patch source. Please see build log for info.
```

shouldn't that be running on 3.10 or perhaps it's in the build part.

**Comment by jakirkham** [comment]
Should be resolved by PR ( https://github.com/conda-forge/numba-feedstock/pull/94 ) and other related upstream PRs
